### ISSUE TITLE
Model build problems

### ISSUE THREAD

**Issue by librahfacebook** [guyuchao/PyramidCSA#1]
你好，我这里在将PCSA_Model模块进行打包时，始终出现一些问题，无法正常使用，想问一下当初你怎么进行模块封装的。非常感谢！！！可以加个联系方式了解一下吗？QQ: 428475501

**Comment by guyuchao** [comment]
> 你好，我这里在将PCSA_Model模块进行打包时，始终出现一些问题，无法正常使用，想问一下当初你怎么进行模块封装的。非常感谢！！！可以加个联系方式了解一下吗？QQ: 428475501

Please describe the detailed problem you meet.
