### ISSUE TITLE
DDP Module training stuck

### ISSUE THREAD

**Issue by lawrence-cj** [guyuchao/PyramidCSA#14]
Hi Prof., when I was training the model, I stuck at random epochs. Have u ever met this situation and is there any suggestion for this problem?

**Comment by guyuchao** [comment]
I haven't met this problem. You can provide some more details about your environment.

**Comment by lawrence-cj** [comment]
ubuntu18.01
GPU: 2080ti x8
torch1.1
python3.6

**Comment by guyuchao** [comment]
You can provide more details, like providing the screenshot when you kill the process. You can email me your wechat and I will add your wechat for convenience.

**Comment by lawrence-cj** [comment]
ok, thank you so much
