### ISSUE TITLE
undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by GewelsJI** [guyuchao/PyramidCSA#2]
I face this problem when I run the script 'PCSA.py'
```
    import self_cuda_backend as _ext
ImportError: /xxxxxxx/Models/PCSA/self_cuda_backend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

```

how to solve it? please help me, thank you!

**Comment by guyuchao** [comment]
What version of cuda you used to build?

**Comment by GewelsJI** [comment]
cuda10.0

**Comment by guyuchao** [comment]
please check your pytorch version>=1.1.0, and system cuda=10.0 and conda cudatoolkit=10.0

**Comment by GewelsJI** [comment]
thanks, i will try it again

**Comment by panmyuan** [comment]
> thanks, i will try it again

Hello, I have some problems about it. Could you give me some advices？I don’t run it. I don’t know disturbed training.
